### ISSUE TITLE
Multiple thermostats query

### ISSUE THREAD

**Issue by jamessimpson007** [gekkekoe/esphome-ecodan-remote-thermostat#4]
Hi, I’m hoping you can help me understand something?

Thanks for creating such an interesting and useful project. I’m having fun playing around with your remote thermostat package, which is generally excellent and helping me run my Ecodan in AA mode which is much better for controlling cycling in mild ambient temperatures. 

I have 4 rooms set up. I’m struggling to understand why the current_temperature of the remote thermostats which have been created in HA don’t all update my FTC5 controller as expected. I have set everything up as described in the readme, and I can control the target temperature as expected. The Target Temperature on the FTC5 changes as expected when I change any of these 4, either using the climate controller in HA, or via the “Climate: Set target temperature” service call or using an automation. 

However, the current_temperature on my FTC5 only updates in response to changes generated in HA of my first remote thermostat (thermostat-room-0), not the other 3. 

```
packages:
# up to 8 thermostats can be defined. 0-7.
  thermostat-room-0: !include { file: confs/thermostat-room.yaml, vars: { room_identifier: 0, room_name: "Radiators Average" } }
  thermostat-room-1: !include { file: confs/thermostat-room.yaml, vars: { room_identifier: 1, room_name: "Hallway" } }
  thermostat-room-2: !include { file: confs/thermostat-room.yaml, vars: { room_identifier: 2, room_name: "Sitting Room" } }
  thermostat-room-3: !include { file: confs/thermostat-room.yaml, vars: { room_identifier: 3, room_name: "Spare Room" } }
  ```

From reading the Mitsubishi docs I understand that when more than one remote thermostat is in use, the FTC5 uses the values from the last one to have been updated. However, for mine this only seems to apply to the target temperatures, not the current temperatures. Am I missing something fundamentally stupid?
